ALTER TABLE DART."Cliente" ADD "CEP" VARCHAR2(8);
ALTER TABLE DART."Cliente" ADD "Endereco" VARCHAR2(76);
ALTER TABLE DART."Cliente" ADD "Numero" VARCHAR2(6);
ALTER TABLE DART."Cliente" ADD "Telefone" VARCHAR2(13);
ALTER TABLE DART."Cliente" ADD "UF" VARCHAR2(2);
ALTER TABLE DART."Cliente" ADD "Cidade" VARCHAR2(50);

ALTER TABLE DART."Cliente" MODIFY CEP VARCHAR2(8) NOT NULL;
ALTER TABLE DART."Cliente" MODIFY "Endereco" VARCHAR2(76) NOT NULL;
ALTER TABLE DART."Cliente" MODIFY "Numero" VARCHAR2(6) NOT NULL;
ALTER TABLE DART."Cliente" MODIFY "Telefone" VARCHAR2(13) NOT NULL;
ALTER TABLE DART."Cliente" MODIFY UF VARCHAR2(2) NOT NULL;
ALTER TABLE DART."Cliente" MODIFY "Cidade" VARCHAR2(50) NOT NULL;

