//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWLog.Web.Backoffice.GlobalResources.Common.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string ActionsLabel {
            get {
                return ResourceManager.GetString("ActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log de Erro.
        /// </summary>
        public static string ApplicationLogMenuItem {
            get {
                return ResourceManager.GetString("ApplicationLogMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BackAction {
            get {
                return ResourceManager.GetString("BackAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string BOAccountMenuItem {
            get {
                return ResourceManager.GetString("BOAccountMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log de Auditoria.
        /// </summary>
        public static string BOLogSystemMenuItem {
            get {
                return ResourceManager.GetString("BOLogSystemMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa alterada com sucesso..
        /// </summary>
        public static string ChangeCompanySuccess {
            get {
                return ResourceManager.GetString("ChangeCompanySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string ChangePasswordAction {
            get {
                return ResourceManager.GetString("ChangePasswordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar Todos.
        /// </summary>
        public static string CheckAllLabel {
            get {
                return ResourceManager.GetString("CheckAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string ClearAction {
            get {
                return ResourceManager.GetString("ClearAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string ConfigurationMenuGroup {
            get {
                return ResourceManager.GetString("ConfigurationMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string CreateAction {
            get {
                return ResourceManager.GetString("CreateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        public static string CreateBreadcrumbItem {
            get {
                return ResourceManager.GetString("CreateBreadcrumbItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualização.
        /// </summary>
        public static string DetailsBreadcrumbItem {
            get {
                return ResourceManager.GetString("DetailsBreadcrumbItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvido por.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditAction {
            get {
                return ResourceManager.GetString("EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edição.
        /// </summary>
        public static string EditBreadcrumbItem {
            get {
                return ResourceManager.GetString("EditBreadcrumbItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string FilterHeader {
            get {
                return ResourceManager.GetString("FilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string GroupMenuItem {
            get {
                return ResourceManager.GetString("GroupMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string HomeMenuItem {
            get {
                return ResourceManager.GetString("HomeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista.
        /// </summary>
        public static string ListHeader {
            get {
                return ResourceManager.GetString("ListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string LogOffAction {
            get {
                return ResourceManager.GetString("LogOffAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebimento.
        /// </summary>
        public static string MenuRecebimento {
            get {
                return ResourceManager.GetString("MenuRecebimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiquetas.
        /// </summary>
        public static string MenuRecebimentoeEtiquetas {
            get {
                return ResourceManager.GetString("MenuRecebimentoeEtiquetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string MenuRecebimentoNotas {
            get {
                return ResourceManager.GetString("MenuRecebimentoNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarentena.
        /// </summary>
        public static string MenuRecebimentoQuarentena {
            get {
                return ResourceManager.GetString("MenuRecebimentoQuarentena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        public static string MenuRecebimentoRelatorios {
            get {
                return ResourceManager.GetString("MenuRecebimentoRelatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressoras.
        /// </summary>
        public static string PrinterMenuItem {
            get {
                return ResourceManager.GetString("PrinterMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de impressora.
        /// </summary>
        public static string PrinterTypeMenuItem {
            get {
                return ResourceManager.GetString("PrinterTypeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar este registro..
        /// </summary>
        public static string RegisterCreatedErrorMessage {
            get {
                return ResourceManager.GetString("RegisterCreatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro criado com sucesso..
        /// </summary>
        public static string RegisterCreatedSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterCreatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído com sucesso..
        /// </summary>
        public static string RegisterDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterDeletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível editar o registro..
        /// </summary>
        public static string RegisterEditedErrorMessage {
            get {
                return ResourceManager.GetString("RegisterEditedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro editado com sucesso..
        /// </summary>
        public static string RegisterEditedSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterEditedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro não pode ser apagado pois possui vínculos..
        /// </summary>
        public static string RegisterHasRelationshipsErrorMessage {
            get {
                return ResourceManager.GetString("RegisterHasRelationshipsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro(s) excluído(s) com sucesso..
        /// </summary>
        public static string RegisterMassDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterMassDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado..
        /// </summary>
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro inesperado durante a requisição..
        /// </summary>
        public static string RequestUnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("RequestUnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string SearchAction {
            get {
                return ResourceManager.GetString("SearchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string SendAction {
            get {
                return ResourceManager.GetString("SendAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desmarcar Todos.
        /// </summary>
        public static string UncheckAllLabel {
            get {
                return ResourceManager.GetString("UncheckAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        public static string UserMenuGroup {
            get {
                return ResourceManager.GetString("UserMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string ViewAction {
            get {
                return ResourceManager.GetString("ViewAction", resourceCulture);
            }
        }
    }
}
