//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWLog.Data.GlobalResources.Mail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWLog.Data.GlobalResources.Mail.MailStrings", typeof(MailStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        public static string RecoverPassword_Part1 {
            get {
                return ResourceManager.GetString("RecoverPassword_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi solicitado pelo sistema a recuperação da senha do seu usuário. Clique.
        /// </summary>
        public static string RecoverPassword_Part2 {
            get {
                return ResourceManager.GetString("RecoverPassword_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aqui.
        /// </summary>
        public static string RecoverPassword_Part3 {
            get {
                return ResourceManager.GetString("RecoverPassword_Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para definir uma nova senha..
        /// </summary>
        public static string RecoverPassword_Part4 {
            get {
                return ResourceManager.GetString("RecoverPassword_Part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso não tenha solicitado a recuperação da senha, ignore esse e-mail..
        /// </summary>
        public static string RecoverPassword_Part5 {
            get {
                return ResourceManager.GetString("RecoverPassword_Part5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperação de Senha.
        /// </summary>
        public static string RecoverPassword_Subject {
            get {
                return ResourceManager.GetString("RecoverPassword_Subject", resourceCulture);
            }
        }
    }
}
