//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BOLogSystemStrings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BOLogSystemStrings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWLog.Web.Backoffice.GlobalResources.BOLogSystem.BOLogSystemStrings", typeof(BOLogSystemStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ação.
        /// </summary>
        public static string ActionTypeLabel
        {
            get
            {
                return ResourceManager.GetString("ActionTypeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string DescriptionTypeLabel
        {
            get
            {
                return ResourceManager.GetString("DescriptionTypeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visualização de Log de Auditoria.
        /// </summary>
        public static string DetailsPageTitle
        {
            get
            {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        public static string EntityLabel
        {
            get
            {
                return ResourceManager.GetString("EntityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        public static string ExecutionDateEndLabel
        {
            get
            {
                return ResourceManager.GetString("ExecutionDateEndLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data de Execução.
        /// </summary>
        public static string ExecutionDateLabel
        {
            get
            {
                return ResourceManager.GetString("ExecutionDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        public static string ExecutionDateStartLabel
        {
            get
            {
                return ResourceManager.GetString("ExecutionDateStartLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campo.
        /// </summary>
        public static string FieldLabel
        {
            get
            {
                return ResourceManager.GetString("FieldLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string IdBOLogSistemLabel
        {
            get
            {
                return ResourceManager.GetString("IdBOLogSistemLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lista de Log de Auditoria.
        /// </summary>
        public static string IndexPageTitle
        {
            get
            {
                return ResourceManager.GetString("IndexPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IPLabel
        {
            get
            {
                return ResourceManager.GetString("IPLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        public static string LabelAll
        {
            get
            {
                return ResourceManager.GetString("LabelAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log de Auditoria.
        /// </summary>
        public static string LogHeader
        {
            get
            {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valor Novo.
        /// </summary>
        public static string NewValueLabel
        {
            get
            {
                return ResourceManager.GetString("NewValueLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valor Anterior.
        /// </summary>
        public static string PreviousValueLabel
        {
            get
            {
                return ResourceManager.GetString("PreviousValueLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logs Relacionados.
        /// </summary>
        public static string RelatedLogsHeader
        {
            get
            {
                return ResourceManager.GetString("RelatedLogsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuário.
        /// </summary>
        public static string UserNameLabel
        {
            get
            {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        public static string ValuesHeader
        {
            get
            {
                return ResourceManager.GetString("ValuesHeader", resourceCulture);
            }
        }
    }
}
