//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWLog.Data.GlobalResources.Entity.EntityStrings", typeof(EntityStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicação.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string Application_IdApplication {
            get {
                return ResourceManager.GetString("Application_IdApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        public static string ApplicationLog_Created {
            get {
                return ResourceManager.GetString("ApplicationLog_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceção.
        /// </summary>
        public static string ApplicationLog_Exception {
            get {
                return ResourceManager.GetString("ApplicationLog_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador da Aplicação.
        /// </summary>
        public static string ApplicationLog_IdApplication {
            get {
                return ResourceManager.GetString("ApplicationLog_IdApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string ApplicationLog_IdApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog_IdApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível.
        /// </summary>
        public static string ApplicationLog_Level {
            get {
                return ResourceManager.GetString("ApplicationLog_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string ApplicationLog_Message {
            get {
                return ResourceManager.GetString("ApplicationLog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string aspnet__Users {
            get {
                return ResourceManager.GetString("aspnet__Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador da Aplicação.
        /// </summary>
        public static string aspnet__Users_ApplicationId {
            get {
                return ResourceManager.GetString("aspnet__Users_ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É Anônimo.
        /// </summary>
        public static string aspnet__Users_IsAnonymous {
            get {
                return ResourceManager.GetString("aspnet__Users_IsAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Ultima Atividade.
        /// </summary>
        public static string aspnet__Users_LastActivityDate {
            get {
                return ResourceManager.GetString("aspnet__Users_LastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuário Minúsculo.
        /// </summary>
        public static string aspnet__Users_LoweredUserName {
            get {
                return ResourceManager.GetString("aspnet__Users_LoweredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Móvel.
        /// </summary>
        public static string aspnet__Users_MobileAlias {
            get {
                return ResourceManager.GetString("aspnet__Users_MobileAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string aspnet__Users_UserId {
            get {
                return ResourceManager.GetString("aspnet__Users_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuário.
        /// </summary>
        public static string aspnet__Users_UserName {
            get {
                return ResourceManager.GetString("aspnet__Users_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string AspNetRoles {
            get {
                return ResourceManager.GetString("AspNetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string AspNetRoles_Name {
            get {
                return ResourceManager.GetString("AspNetRoles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string AspNetUsers {
            get {
                return ResourceManager.GetString("AspNetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuário.
        /// </summary>
        public static string AspNetUsers_UserName {
            get {
                return ResourceManager.GetString("AspNetUsers_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string BOGroup {
            get {
                return ResourceManager.GetString("BOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string BOGroup_IdBOGroup {
            get {
                return ResourceManager.GetString("BOGroup_IdBOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string BOGroup_Name {
            get {
                return ResourceManager.GetString("BOGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papel do Grupo.
        /// </summary>
        public static string BOGroupRoles {
            get {
                return ResourceManager.GetString("BOGroupRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string BOGroupRoles_IdBOGroup {
            get {
                return ResourceManager.GetString("BOGroupRoles_IdBOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Papel.
        /// </summary>
        public static string BOGroupRoles_RoleName {
            get {
                return ResourceManager.GetString("BOGroupRoles_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string BOLogSystem {
            get {
                return ResourceManager.GetString("BOLogSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Ação.
        /// </summary>
        public static string BOLogSystem_ActionType {
            get {
                return ResourceManager.GetString("BOLogSystem_ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string BOLogSystem_Description {
            get {
                return ResourceManager.GetString("BOLogSystem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        public static string BOLogSystem_Entity {
            get {
                return ResourceManager.GetString("BOLogSystem_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Execução.
        /// </summary>
        public static string BOLogSystem_ExecutionDate {
            get {
                return ResourceManager.GetString("BOLogSystem_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string BOLogSystem_IdBOLogSistem {
            get {
                return ResourceManager.GetString("BOLogSystem_IdBOLogSistem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string BOLogSystem_IP {
            get {
                return ResourceManager.GetString("BOLogSystem_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Entidade.
        /// </summary>
        public static string BOLogSystem_NewEntity {
            get {
                return ResourceManager.GetString("BOLogSystem_NewEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade Antiga.
        /// </summary>
        public static string BOLogSystem_OldEntity {
            get {
                return ResourceManager.GetString("BOLogSystem_OldEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador do Usuário.
        /// </summary>
        public static string BOLogSystem_UserId {
            get {
                return ResourceManager.GetString("BOLogSystem_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperação de Senha BackOffice.
        /// </summary>
        public static string BORecoveryPassword {
            get {
                return ResourceManager.GetString("BORecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        public static string BORecoveryPassword_Created {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string BORecoveryPassword_Email {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string BORecoveryPassword_IdBORecoveryPassword {
            get {
                return ResourceManager.GetString("BORecoveryPassword_IdBORecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string BORecoveryPassword_Token {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usado.
        /// </summary>
        public static string BORecoveryPassword_Used {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador do Usuário.
        /// </summary>
        public static string BORecoveryPassword_UserId {
            get {
                return ResourceManager.GetString("BORecoveryPassword_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valido Até.
        /// </summary>
        public static string BORecoveryPassword_ValidThru {
            get {
                return ResourceManager.GetString("BORecoveryPassword_ValidThru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Usuário.
        /// </summary>
        public static string BOUserGroup {
            get {
                return ResourceManager.GetString("BOUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string BOUserGroup_IdBOGroup {
            get {
                return ResourceManager.GetString("BOUserGroup_IdBOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuário.
        /// </summary>
        public static string BOUserGroup_UserName {
            get {
                return ResourceManager.GetString("BOUserGroup_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RazãoSocial.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Empresa.
        /// </summary>
        public static string IdCompany {
            get {
                return ResourceManager.GetString("IdCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segurança de Aplicação.
        /// </summary>
        public static string SecurityApplication {
            get {
                return ResourceManager.GetString("SecurityApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        public static string SecurityApplication_Created {
            get {
                return ResourceManager.GetString("SecurityApplication_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitado.
        /// </summary>
        public static string SecurityApplication_Disabled {
            get {
                return ResourceManager.GetString("SecurityApplication_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string SecurityApplication_IdSecurityApplication {
            get {
                return ResourceManager.GetString("SecurityApplication_IdSecurityApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string SecurityApplication_Password {
            get {
                return ResourceManager.GetString("SecurityApplication_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuário.
        /// </summary>
        public static string SecurityApplication_Username {
            get {
                return ResourceManager.GetString("SecurityApplication_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão de Segurança.
        /// </summary>
        public static string SecurityPermission {
            get {
                return ResourceManager.GetString("SecurityPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        public static string SecurityPermission_Created {
            get {
                return ResourceManager.GetString("SecurityPermission_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string SecurityPermission_Description {
            get {
                return ResourceManager.GetString("SecurityPermission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string SecurityPermission_IdSecurityPermission {
            get {
                return ResourceManager.GetString("SecurityPermission_IdSecurityPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string SecurityPermission_Name {
            get {
                return ResourceManager.GetString("SecurityPermission_Name", resourceCulture);
            }
        }
    }
}
