//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityStrings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWLog.Data.GlobalResources.Entity.EntityStrings", typeof(EntityStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aplicação.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string Application_IdApplication {
            get {
                return ResourceManager.GetString("Application_IdApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código da Aplicação.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string ApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criação.
        /// </summary>
        public static string ApplicationLog_Created {
            get {
                return ResourceManager.GetString("ApplicationLog_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exceção.
        /// </summary>
        public static string ApplicationLog_Exception {
            get {
                return ResourceManager.GetString("ApplicationLog_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador da Aplicação.
        /// </summary>
        public static string ApplicationLog_IdApplication {
            get {
                return ResourceManager.GetString("ApplicationLog_IdApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string ApplicationLog_IdApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog_IdApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nível.
        /// </summary>
        public static string ApplicationLog_Level {
            get {
                return ResourceManager.GetString("ApplicationLog_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensagem.
        /// </summary>
        public static string ApplicationLog_Message {
            get {
                return ResourceManager.GetString("ApplicationLog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string aspnet__Users {
            get {
                return ResourceManager.GetString("aspnet__Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador da Aplicação.
        /// </summary>
        public static string aspnet__Users_ApplicationId {
            get {
                return ResourceManager.GetString("aspnet__Users_ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É Anônimo.
        /// </summary>
        public static string aspnet__Users_IsAnonymous {
            get {
                return ResourceManager.GetString("aspnet__Users_IsAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data da Ultima Atividade.
        /// </summary>
        public static string aspnet__Users_LastActivityDate {
            get {
                return ResourceManager.GetString("aspnet__Users_LastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuário Minúsculo.
        /// </summary>
        public static string aspnet__Users_LoweredUserName {
            get {
                return ResourceManager.GetString("aspnet__Users_LoweredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alias Móvel.
        /// </summary>
        public static string aspnet__Users_MobileAlias {
            get {
                return ResourceManager.GetString("aspnet__Users_MobileAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string aspnet__Users_UserId {
            get {
                return ResourceManager.GetString("aspnet__Users_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuário.
        /// </summary>
        public static string aspnet__Users_UserName {
            get {
                return ResourceManager.GetString("aspnet__Users_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo.
        /// </summary>
        public static string AspNetRoles {
            get {
                return ResourceManager.GetString("AspNetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string AspNetRoles_Name {
            get {
                return ResourceManager.GetString("AspNetRoles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string AspNetUsers {
            get {
                return ResourceManager.GetString("AspNetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuário.
        /// </summary>
        public static string AspNetUsers_UserName {
            get {
                return ResourceManager.GetString("AspNetUsers_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo.
        /// </summary>
        public static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo.
        /// </summary>
        public static string BOGroup {
            get {
                return ResourceManager.GetString("BOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string BOGroup_IdBOGroup {
            get {
                return ResourceManager.GetString("BOGroup_IdBOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string BOGroup_Name {
            get {
                return ResourceManager.GetString("BOGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Papel do Grupo.
        /// </summary>
        public static string BOGroupRoles {
            get {
                return ResourceManager.GetString("BOGroupRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string BOGroupRoles_IdBOGroup {
            get {
                return ResourceManager.GetString("BOGroupRoles_IdBOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Papel.
        /// </summary>
        public static string BOGroupRoles_RoleName {
            get {
                return ResourceManager.GetString("BOGroupRoles_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log.
        /// </summary>
        public static string BOLogSystem {
            get {
                return ResourceManager.GetString("BOLogSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Ação.
        /// </summary>
        public static string BOLogSystem_ActionType {
            get {
                return ResourceManager.GetString("BOLogSystem_ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        public static string BOLogSystem_Description {
            get {
                return ResourceManager.GetString("BOLogSystem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entidade.
        /// </summary>
        public static string BOLogSystem_Entity {
            get {
                return ResourceManager.GetString("BOLogSystem_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Execução.
        /// </summary>
        public static string BOLogSystem_ExecutionDate {
            get {
                return ResourceManager.GetString("BOLogSystem_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string BOLogSystem_IdBOLogSistem {
            get {
                return ResourceManager.GetString("BOLogSystem_IdBOLogSistem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IP.
        /// </summary>
        public static string BOLogSystem_IP {
            get {
                return ResourceManager.GetString("BOLogSystem_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova Entidade.
        /// </summary>
        public static string BOLogSystem_NewEntity {
            get {
                return ResourceManager.GetString("BOLogSystem_NewEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entidade Antiga.
        /// </summary>
        public static string BOLogSystem_OldEntity {
            get {
                return ResourceManager.GetString("BOLogSystem_OldEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador do Usuário.
        /// </summary>
        public static string BOLogSystem_UserId {
            get {
                return ResourceManager.GetString("BOLogSystem_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recuperação de Senha BackOffice.
        /// </summary>
        public static string BORecoveryPassword {
            get {
                return ResourceManager.GetString("BORecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criação.
        /// </summary>
        public static string BORecoveryPassword_Created {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        public static string BORecoveryPassword_Email {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string BORecoveryPassword_IdBORecoveryPassword {
            get {
                return ResourceManager.GetString("BORecoveryPassword_IdBORecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token.
        /// </summary>
        public static string BORecoveryPassword_Token {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usado.
        /// </summary>
        public static string BORecoveryPassword_Used {
            get {
                return ResourceManager.GetString("BORecoveryPassword_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador do Usuário.
        /// </summary>
        public static string BORecoveryPassword_UserId {
            get {
                return ResourceManager.GetString("BORecoveryPassword_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valido Até.
        /// </summary>
        public static string BORecoveryPassword_ValidThru {
            get {
                return ResourceManager.GetString("BORecoveryPassword_ValidThru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo de Usuário.
        /// </summary>
        public static string BOUserGroup {
            get {
                return ResourceManager.GetString("BOUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string BOUserGroup_IdBOGroup {
            get {
                return ResourceManager.GetString("BOUserGroup_IdBOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuário.
        /// </summary>
        public static string BOUserGroup_UserName {
            get {
                return ResourceManager.GetString("BOUserGroup_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Empresa.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Razão Social.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Nascimento.
        /// </summary>
        public static string DataNascimento {
            get {
                return ResourceManager.GetString("DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Departamento.
        /// </summary>
        public static string Departamento {
            get {
                return ResourceManager.GetString("Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Empresa Principal.
        /// </summary>
        public static string EmpresaPrincipal {
            get {
                return ResourceManager.GetString("EmpresaPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código da Empresa.
        /// </summary>
        public static string IdCompany {
            get {
                return ResourceManager.GetString("IdCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sigla.
        /// </summary>
        public static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Usuário.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do Perfil do Usuário.
        /// </summary>
        public static string PerfilUsuarioId {
            get {
                return ResourceManager.GetString("PerfilUsuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do Grupo.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Grupo.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Segurança de Aplicação.
        /// </summary>
        public static string SecurityApplication {
            get {
                return ResourceManager.GetString("SecurityApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criação.
        /// </summary>
        public static string SecurityApplication_Created {
            get {
                return ResourceManager.GetString("SecurityApplication_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desabilitado.
        /// </summary>
        public static string SecurityApplication_Disabled {
            get {
                return ResourceManager.GetString("SecurityApplication_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string SecurityApplication_IdSecurityApplication {
            get {
                return ResourceManager.GetString("SecurityApplication_IdSecurityApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string SecurityApplication_Password {
            get {
                return ResourceManager.GetString("SecurityApplication_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuário.
        /// </summary>
        public static string SecurityApplication_Username {
            get {
                return ResourceManager.GetString("SecurityApplication_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permissão de Segurança.
        /// </summary>
        public static string SecurityPermission {
            get {
                return ResourceManager.GetString("SecurityPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criação.
        /// </summary>
        public static string SecurityPermission_Created {
            get {
                return ResourceManager.GetString("SecurityPermission_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        public static string SecurityPermission_Description {
            get {
                return ResourceManager.GetString("SecurityPermission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador.
        /// </summary>
        public static string SecurityPermission_IdSecurityPermission {
            get {
                return ResourceManager.GetString("SecurityPermission_IdSecurityPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string SecurityPermission_Name {
            get {
                return ResourceManager.GetString("SecurityPermission_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do Usuário.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
