

  CREATE TABLE "DART"."NotaRecebimentoStatus" 
   (	"IdNotaRecebimentoStatus" NUMBER(*,0) NOT NULL ENABLE, 
	"Descricao" VARCHAR2(50), 
	 CONSTRAINT "NotaRecebimentoStatus_PK" PRIMARY KEY ("IdNotaRecebimentoStatus")
  USING INDEX (CREATE UNIQUE INDEX "DART"."NotaRecebimentoStatus_INDEX1" ON "DART"."NotaRecebimentoStatus" ("IdNotaRecebimentoStatus") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
INSERT INTO "NotaRecebimentoStatus" VALUES('1', 'Registrado');
INSERT INTO "NotaRecebimentoStatus" VALUES('2', 'Sincronizado');



INSERT INTO "ImpressaoItem" VALUES('9', 'Etiqueta de Recebimento Sem Nota');
INSERT INTO "TipoEtiquetagem" VALUES('7', 'RecebimentoSemNota');