//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BOAccountStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BOAccountStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWLog.Web.Backoffice.GlobalResources.BOAccount.BOAccountStrings", typeof(BOAccountStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Senha.
        /// </summary>
        public static string ChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar Todos.
        /// </summary>
        public static string CheckAllLabel {
            get {
                return ResourceManager.GetString("CheckAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha e a confirmação da nova senha não estão iguais..
        /// </summary>
        public static string ConfirmNewPasswordCompareMessage {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordCompareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação Nova Senha.
        /// </summary>
        public static string ConfirmNewPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e a confirmação de senha devem ser iguais..
        /// </summary>
        public static string ConfirmPasswordCompareMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Senha.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação de Usuário.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Criação.
        /// </summary>
        public static string CreationDateLabel {
            get {
                return ResourceManager.GetString("CreationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual inválida..
        /// </summary>
        public static string CurrentPasswordInvalidMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir {0} registro(s)?.
        /// </summary>
        public static string DeleteMassModalMessage {
            get {
                return ResourceManager.GetString("DeleteMassModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir esse registro?.
        /// </summary>
        public static string DeleteModalMessage {
            get {
                return ResourceManager.GetString("DeleteModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string DeleteModalTitle {
            get {
                return ResourceManager.GetString("DeleteModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualização de Usuário.
        /// </summary>
        public static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo?.
        /// </summary>
        public static string DisabledLabel {
            get {
                return ResourceManager.GetString("DisabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edição de Usuário.
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos.
        /// </summary>
        public static string GroupsHeader {
            get {
                return ResourceManager.GetString("GroupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Usuário.
        /// </summary>
        public static string IndexPageTitle {
            get {
                return ResourceManager.GetString("IndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro não reconhecido. Por favor, verifique seus dados e tente novamente. Se o problema persistir, por favor contate o administrador..
        /// </summary>
        public static string MembershipDefaultErrorMessage {
            get {
                return ResourceManager.GetString("MembershipDefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este email está em uso por outro usuário. Por favor, escolha outro..
        /// </summary>
        public static string MembershipDuplicateEmailMessage {
            get {
                return ResourceManager.GetString("MembershipDuplicateEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário existente. Por favor, escolha outro..
        /// </summary>
        public static string MembershipDuplicateUserNameMessage {
            get {
                return ResourceManager.GetString("MembershipDuplicateUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resposta de requisição de senha está errada. Por favor, corrija-a..
        /// </summary>
        public static string MembershipInvalidAnswerMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email informado é inválido. Por favor, corrija-o..
        /// </summary>
        public static string MembershipInvalidEmailMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é inválida. Por favor, escolha outra..
        /// </summary>
        public static string MembershipInvalidPasswordMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pergunta de requisição de senha está errada. Por favor, corrija-a..
        /// </summary>
        public static string MembershipInvalidQuestionMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário está inválido. Por favor, corrija-o..
        /// </summary>
        public static string MembershipInvalidUserNameMessage {
            get {
                return ResourceManager.GetString("MembershipInvalidUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A autenticação retornou um erro. Por favor, verifique seus dados e tente novamente. Se o problema persistir, por favor contate o administrador..
        /// </summary>
        public static string MembershipProviderErrorMessage {
            get {
                return ResourceManager.GetString("MembershipProviderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A criação do usuário foi cancelada. Por favor, verifique seus dados e tente novamente. Se o problema persistir, por favor contate o administrador..
        /// </summary>
        public static string MembshipUserRejectedMessage {
            get {
                return ResourceManager.GetString("MembshipUserRejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Usuário.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string OldPasswordLabel {
            get {
                return ResourceManager.GetString("OldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso..
        /// </summary>
        public static string PasswordChangedSuccessMessage {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string PasswordHeader {
            get {
                return ResourceManager.GetString("PasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacione o usuário ao menos à uma empresa..
        /// </summary>
        public static string RequiredOnlyCompany {
            get {
                return ResourceManager.GetString("RequiredOnlyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacione pelo menos um grupo à empresa adicionada ao usuário..
        /// </summary>
        public static string RequiredOnlyGroup {
            get {
                return ResourceManager.GetString("RequiredOnlyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetar Senha.
        /// </summary>
        public static string ResetPasswordAction {
            get {
                return ResourceManager.GetString("ResetPasswordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente resetar a senha desse usuário?.
        /// </summary>
        public static string ResetPasswordModalMessage {
            get {
                return ResourceManager.GetString("ResetPasswordModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string ResetPasswordModalTitle {
            get {
                return ResourceManager.GetString("ResetPasswordModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string SearchAction {
            get {
                return ResourceManager.GetString("SearchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desmarcar Todos.
        /// </summary>
        public static string UncheckAllLabel {
            get {
                return ResourceManager.GetString("UncheckAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear.
        /// </summary>
        public static string UnlockAction {
            get {
                return ResourceManager.GetString("UnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente desbloquear {0} usuário(s)?.
        /// </summary>
        public static string UnlockMassModalMessage {
            get {
                return ResourceManager.GetString("UnlockMassModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente desbloquear esse usuário?.
        /// </summary>
        public static string UnlockModalMessage {
            get {
                return ResourceManager.GetString("UnlockModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string UnlockModalTitle {
            get {
                return ResourceManager.GetString("UnlockModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com esse e-mail. Por favor escolha outro..
        /// </summary>
        public static string UserEmailAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("UserEmailAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string UserHeader {
            get {
                return ResourceManager.GetString("UserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao desbloquear o(s) usuário(s). Por favor, tente novamente. Se o problema persistir contate o administrador do sistema..
        /// </summary>
        public static string UserMassUnlockErrorMessage {
            get {
                return ResourceManager.GetString("UserMassUnlockErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário(s) desbloqueado(s) com sucesso..
        /// </summary>
        public static string UserMassUnlockSuccessMessage {
            get {
                return ResourceManager.GetString("UserMassUnlockSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com esse nome. Por favor escolha outro..
        /// </summary>
        public static string UserNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("UserNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Usuário.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao resetar a senha do usuário. Por favor, tente novamente. Se o problema persistir contate o administrador do sistema..
        /// </summary>
        public static string UserPasswordResetErrorMessage {
            get {
                return ResourceManager.GetString("UserPasswordResetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha resetada com sucesso para o usuário: {0}. A nova senha é: {1}.
        /// </summary>
        public static string UserPasswordResetSuccessMessage {
            get {
                return ResourceManager.GetString("UserPasswordResetSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao desbloquear usuário. Por favor, tente novamente. Se o problema persistir contate o administrador do sistema..
        /// </summary>
        public static string UserUnlockedErrorMessage {
            get {
                return ResourceManager.GetString("UserUnlockedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário desbloqueado com sucesso..
        /// </summary>
        public static string UserUnlockedSuccessMessage {
            get {
                return ResourceManager.GetString("UserUnlockedSuccessMessage", resourceCulture);
            }
        }
    }
}
